apiVersion: apps/v1
kind: Deployment
metadata:
  name: diana-nodeapp
  labels:
    app: diana-nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diana-nodeapp
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: diana-nodeapp
    spec:
      containers:
      - name: diana-nodeapp
        image: gcr.io/lbg-training/diana-nodeapp:11
        ports:
        - containerPort: 5000