kind: Service
apiVersion: v1
metadata:
  name: diana-nodeapp-lb
spec:
  type: LoadBalancer
  selector:
    app: diana-nodeapp
  ports:
  - protocol: TCP
    port: 80        # Defines the Service's port within the cluster
    targetPort: 5000  # Defines the Pod's port